service_type: NodePort
service_port: "{{ jenkins_nodeport }}"
persistence_storageClassName: rook-ceph-block
persistence_size: 8Gi
rbac_create: true

#jenkins_image: jenkins/jenkins
jenkins_chart: cloudbees/cloudbees-core
jenkins_chart_version: 3.28.1+3c5f25973d17
jenkins_namespace: jenkins
jenkins_name: jenkins
