---
# #####################################################################
# Terminate MOADSD-NG Environment
# #####################################################################
- name: Terminate MOADSD-NG Environment
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    scopes:
      - https://www.googleapis.com/auth/compute
    terminate_jumphost: False

  tasks:
    - name: Include vars
      include: site_vars.yml

    - name: Delete subdirectory host_vars
      file:
        path: "./host_vars"
        state: absent

    - name: Find yml files in group_vars
      find:
        paths: "./group_vars"
        patterns: "*.yml"
      register: files_to_delete

    - name: Delete yml files in group_vars
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Delete subdirectory site
      file:
        path: "./site_{{ type }}"
        state: absent

    - name: Terminate GCP environment
      include: stop_gcp.yml
      when: type == 'gcp'

    - name: Terminate AWS environment
      include: stop_aws.yml
      when: type == 'aws'
